In [ ]:
# clone Tuan's resyslab
import os
if not os.path.exists('/kaggle/working/resyslab_utils'):
    !git clone --branch DEV https://github.com/Azure2212/resyslab_utils.git

In [ ]:
 # connect kaggle(remote) to visual studio code(local)
%run /kaggle/working/resyslab_utils/resyslab_utils/clouds/connect_vsc.py

In [ ]:
%run /kaggle/working/read.py

In [7]:
import pandas as pd

# Read the HDF5 file into a DataFrame
df = pd.read_hdf("/kaggle/input/dataset/rafdb_basic.hdf5")

# Select specific columns and print the corresponding rows
selected_columns = [ "age", "emotion","gender", "race"]
selected_data = df.loc[:, selected_columns]
# print( selected_data.loc[selected_data['age']== 4])
selected_data.describe()

                age       emotion        gender          race
count  15339.000000  15339.000000  15339.000000  15339.000000
mean       1.833822      4.479953      0.657409      0.390638
std        0.917919      1.770850      0.590968      0.741857
min        0.000000      1.000000      0.000000      0.000000
25%        1.000000      4.000000      0.000000      0.000000
50%        2.000000      4.000000      1.000000      0.000000
75%        2.000000      6.000000      1.000000      0.000000
max        4.000000      7.000000      2.000000      2.000000

In [ ]:
filtered_data=selected_data.sort_values(by='race')
print(filtered_data.head(11504))

In [15]:
print ('Last rows')
print(selected_data.tail(10))

Last rows
       age  emotion  gender  race
15329    1        7       1     0
15330    2        7       0     0
15331    2        7       1     0
15332    2        7       1     0
15333    1        7       0     0
15334    0        7       2     0
15335    2        7       0     0
15336    2        7       1     2
15337    2        7       0     0
15338    4        7       0     0

In [ ]:
selected_data.corr()

In [ ]:
selected_data.corr(method='kendall') # Tính toán hệ số tương quan Kendall

In [ ]:
selected_data.corr(method='pearson') # Tính toán hệ số tương quan Pearson

In [ ]:
selected_data.corr(method='spearman')

In [ ]:
selected_data.describe()

In [ ]:
# Count rows where 'race' is 0 and 'age' is 0
count_condition_0 = ((df['gender'] == 0) & (df['age'] == 2)).sum()
count_condition_1 = ((df['gender'] == 1) & (df['age'] == 2)).sum()
count_condition_2 = ((df['gender'] == 2) & (df['age'] == 2)).sum()
# Print the count along with a descriptive string
print("Number of rows with race = 0 and age = 2: " + str(count_condition_0))
#cách 2 :count_condition_2 = len(df[(df['gender'] == 2) & (df['age'] == 2)])
print("Number of rows with race = 1 and age = 2: " + str(count_condition_1))
print("Number of rows with race = 2 and age = 2: " + str(count_condition_2))

In [8]:
print( selected_data.emotion.value_counts())
print( selected_data.age.value_counts())
print( selected_data.gender.value_counts())
print( selected_data.race.value_counts())

emotion
4    5957
7    3204
5    2460
1    1619
3     877
6     867
2     355
Name: count, dtype: int64
age
2    8193
1    2657
3    2422
0    1612
4     455
Name: count, dtype: int64
gender
1    8182
0    6206
2     951
Name: count, dtype: int64
race
0    11742
2     2395
1     1202
Name: count, dtype: int64

In [ ]:
! pip show pandas_profiling

In [ ]:
!pip install ydata-profiling

In [9]:
#### hien bang thong ke
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

# Read the HDF5 file into a DataFrame
df = pd.read_hdf("/kaggle/input/dataset/rafdb_basic.hdf5")

# Select specific columns and print the corresponding rows
selected_columns = ["type","gender", "age", "emotion", "race"]
df_train = df.loc[:, selected_columns]

profile = ProfileReport(
    df_train, title="Pandas Profiling Report for rafdb_basic dataset"
)

profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Đọc tệp HDF5 vào DataFrame
df = pd.read_hdf("/kaggle/input/dataset/rafdb_basic.hdf5")

df.loc[df['type']== 'train','type']=0
df.loc[df['type']== 'test','type']=1
# Chọn các cột quan trọng
selected_columns = ['gender', 'age', 'emotion', 'race', "type"]

# Kiểm tra tính tồn tại của các cột trong DataFrame
if all(col in df.columns for col in selected_columns):
    # Lựa chọn các cột
    df_train = df[selected_columns]

    # Thiết lập kích thước hình vẽ và kiểu dáng seaborn
    sns.set(style="whitegrid")# nền chart
    plt.figure(figsize=(8, 10)) #vẽ mới với kích thước là 20x10 inches

    # Tạo pairplot với phân loại màu theo từng cột
    # hue='gender' - biểu đồ scatterplot với phân loại theo gender
    # palette='Set1' - nhóm màu
    pairplot = sns.pairplot(df_train, hue='gender', palette='Set1',kind='scatter', diag_kind='kde',plot_kws=dict(s=80, edgecolor="white", linewidth=2.5))

    # Thêm tiêu đề và điều chỉnh bố cục
    plt.suptitle('Correlogram Chart', y=1)
    plt.tight_layout() # ham dieu chinh tu dong title,chú thích, khoảng cách

    # Hiển thị biểu đồ
    plt.show()
else:
    print("One or more selected columns are not present in the DataFrame.")

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Read the HDF5 file into a DataFrame
df = pd.read_hdf("/kaggle/input/dataset/rafdb_basic.hdf5")

# Verify and correct column names if needed
selected_columns = ['gender', 'age', 'emotion', 'race']

# Check if selected columns are present in DataFrame
if all(col in df.columns for col in selected_columns):
    # Select specific columns
    df_train = df[selected_columns]

    # Calculate the correlation matrix - Tính ma trận tương quan
    corr_matrix = df_train.corr()

    # Set up the matplotlib figure
    plt.figure(figsize=(8, 6)) # độ rộng - dài của ô

    # Create a heatmap with the correlation matrix
    sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', vmin=-1, vmax=1)

    # Add title and show the plot
    plt.title('Heatmap Chart (Correlation Matrix)')
    plt.show()
    
else:
    print("One or more selected columns are not present in the DataFrame.")

In [10]:
import pandas as pd
from ydata_profiling import ProfileReport
# Read the HDF5 file into a DataFrame
df = pd.read_csv("/kaggle/input/dataset/iris.csv")

# Select specific columns and print the corresponding rows
# selected_columns = [ "age", "emotion","gender", "race"]
# selected_data = df.loc[:, selected_columns]
profile = ProfileReport(
    df, title="Pandas Profiling Report for rafdb_basic dataset"
)
# Save the report to an HTML file
#profile.to_file("/kaggle/working/MH_EDA/rafdb_basic_profile.html")
profile.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

VBox(children=(Tab(children=(Tab(children=(GridBox(children=(VBox(children=(GridspecLayout(children=(HTML(valu…

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Đọc dữ liệu từ tập tin CSV
df = sns.load_dataset('iris')

# Vẽ pairplot vẽ với biểu đồ histogram
sns.pairplot(df, kind="hist")
plt.show()

In [ ]:
import pandas as pd
from functools import reduce

df1 = pd.read_table('file1.csv', sep=',')
df2 = pd.read_table('file2.csv', sep=',')
df3 = pd.read_table('file3.csv', sep=',')